---
dependency:
  name: galaxy
  options:
    requirements-file: requirements.yml

driver:
  name: docker

platforms:
  - name: raspi-test
    image: debian:bookworm
    dockerfile: Dockerfile.j2
    privileged: true
    command: /lib/systemd/systemd
    pre_build_image: false
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    cgroupns_mode: host
    tmpfs:
      - /run
      - /tmp

provisioner:
  name: ansible
  env:
    ANSIBLE_FORCE_COLOR: "true"
    ANSIBLE_ROLES_PATH: ../../roles
  inventory:
    host_vars:
      raspi-test:
        ansible_user: root

verifier:
  name: ansible
